### ISSUE TITLE
Scheduler compilation error

### ISSUE THREAD

**Issue by rajikak** [karlseguin/zul#7]
Hello, 

Scheduler library emits the following error: 

```
scheduler.zig:23:61: error: no field named 'fn' in union 'builtin.Type'
        const include_scheduler = @typeInfo(@TypeOf(T.run)).@"fn".params.len == 4;
                                                            ^~~~~
/Users/kumarasiri/installations/zig-macos-aarch64-0.13.0/lib/std/builtin.zig:256:18: note: union declared here
pub const Type = union(enum) {
```

I fixed it by:

```
const include_scheduler = @typeInfo(@TypeOf(T.run)).Fn.params.len == 4; 
```

**Comment by karlseguin** [comment]
Use the [zig-0.13 branch](https://github.com/karlseguin/zul/tree/zig-0.13).

When Zig 0.14 is released (very soon), I'm going to change my projects so that my `master` works with Zig 0.14, and I'll add a 'dev' branch to track Zig master.

**Comment by rajikak** [comment]
Changing the `master` branch to the stable `zig` compiler sounds like a good approach. Thanks.
